// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwZsiosO0kqTVf6kjvzBvRnwWco3dnZLE',
    appId: '1:646283957351:web:833ee1629d98ea812830c2',
    messagingSenderId: '646283957351',
    projectId: 'tache-eade2',
    authDomain: 'tache-eade2.firebaseapp.com',
    storageBucket: 'tache-eade2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFpCAQPQRWR7byj_-xcZGVIwYX3Derxrw',
    appId: '1:646283957351:android:68917b3f56b787e22830c2',
    messagingSenderId: '646283957351',
    projectId: 'tache-eade2',
    storageBucket: 'tache-eade2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6GZNcvHnyeVTmV-Jz3bYse3EOkaUbZv0',
    appId: '1:646283957351:ios:d76f7232aea410732830c2',
    messagingSenderId: '646283957351',
    projectId: 'tache-eade2',
    storageBucket: 'tache-eade2.firebasestorage.app',
    iosBundleId: 'com.example.testapi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6GZNcvHnyeVTmV-Jz3bYse3EOkaUbZv0',
    appId: '1:646283957351:ios:d76f7232aea410732830c2',
    messagingSenderId: '646283957351',
    projectId: 'tache-eade2',
    storageBucket: 'tache-eade2.firebasestorage.app',
    iosBundleId: 'com.example.testapi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBwZsiosO0kqTVf6kjvzBvRnwWco3dnZLE',
    appId: '1:646283957351:web:e6c0b230732f5b5d2830c2',
    messagingSenderId: '646283957351',
    projectId: 'tache-eade2',
    authDomain: 'tache-eade2.firebaseapp.com',
    storageBucket: 'tache-eade2.firebasestorage.app',
  );
}
